{"name": "Неуспешное получение заказов без авторизации - возвращается ожидаемое сообщение", "status": "passed", "start": 1748983319676, "stop": 1748983319857, "uuid": "1e1729d3-7ded-41fd-873e-11ac61663092", "historyId": "49d9bd2d845bb386041bf63db7f5d0ca", "testCaseId": "49d9bd2d845bb386041bf63db7f5d0ca", "fullName": "tests.test_get_orders.TestGetOrdersWithAuth#test_get_orders_without_auth_unauthorized_message", "labels": [{"name": "feature", "value": "Получение заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetOrdersWithAuth"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}