{"name": "Неуспешный логин с неверными учетными данными - возвращается ожидаемый статус 401", "status": "passed", "parameters": [{"name": "wrong_field", "value": "'password'"}], "start": 1748983338153, "stop": 1748983338448, "uuid": "7ce697b4-d0bf-4e47-8967-025471528693", "historyId": "a99907966103a0298a9152231ce73f2a", "testCaseId": "ba27ddf5800cd265d6623d4203d8af65", "fullName": "tests.test_user_login.TestUserLogin#test_login_invalid_credentials_status_401", "labels": [{"name": "feature", "value": "Логин пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}