{"name": "Неуспешное обновление данных пользователя без авторизации - возвращается ожидаемый статус 401", "status": "passed", "parameters": [{"name": "data_field", "value": "'name'"}], "start": 1748983315497, "stop": 1748983315692, "uuid": "407080ed-9236-451d-ace5-298f32db6749", "historyId": "6a0917fdde35e3d12bcda5fbbbbd5de5", "testCaseId": "448204f25e08fe008a9484fb13623fc6", "fullName": "tests.test_edit_user.TestEditUser#test_update_user_without_auth_status_401", "labels": [{"name": "feature", "value": "Изменение данных пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_edit_user"}, {"name": "subSuite", "value": "TestEditUser"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_edit_user"}]}