{"name": "Неуспешный логин с неверными учетными данными - возвращается ожидаемое сообщение", "status": "passed", "parameters": [{"name": "wrong_field", "value": "'email'"}], "start": 1748983339479, "stop": 1748983339667, "uuid": "3f84f28b-6baa-4d7f-b86f-bfa550ca1129", "historyId": "6fc2d40f87f8cf14669f6a791534f825", "testCaseId": "edf1aad5cbc6f9cc3395edceaae049f1", "fullName": "tests.test_user_login.TestUserLogin#test_login_invalid_credentials_message", "labels": [{"name": "feature", "value": "Логин пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}