{"name": "Неуспешное получение заказов без авторизации - возвращается ожидаемый статус 401", "status": "passed", "start": 1748983319491, "stop": 1748983319674, "uuid": "631a071c-eb1d-42c9-80b8-f111dbd5b813", "historyId": "bc52f12b1c5018ceda684a869991e578", "testCaseId": "bc52f12b1c5018ceda684a869991e578", "fullName": "tests.test_get_orders.TestGetOrdersWithAuth#test_get_orders_without_auth_status_401", "labels": [{"name": "feature", "value": "Получение заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "subSuite", "value": "TestGetOrdersWithAuth"}, {"name": "host", "value": "MaxPro"}, {"name": "thread", "value": "2704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}]}